### ISSUE TITLE
Odd envelope behaviour while moving area selection - Area51

### ISSUE THREAD

**Issue by Bird-Bird** [GoranKovac/ReaScripts#11] opened 2020-01-09 19:37 UTC
![5Vag1QyIh2](https://user-images.githubusercontent.com/55462109/72098364-5cb3fb00-332f-11ea-8c1e-7b538a3d66f8.gif)
Envelope points seem to get jumbled up when moving them.

Is there a reason the moving behaviour isn't defined in **AreaDo()** jobs in **Area_51_functions**? I am trying to learn the codebase a bit so I can contribute more. It seems that creating the moving behaviour with pasting and deleting the original area is simpler. Because moving is if you think of it: 
* Paste the items/envelopes in the original area to the target area
* Delete the items in the section in the original area that does not overlap with the target area
Here is a gif of me replicating it with the jobs in AreaDo() instead:
![YgFmlTM4qI](https://user-images.githubusercontent.com/55462109/72098951-9e917100-3330-11ea-9b2f-5adb0211bed3.gif)

**Comment by GoranKovac** [comment] 2020-01-09 20:14
This is the issue I am aware but not yet figured out how to fix. That behavior below seems right to me,
Is that a product of using function in AreaDo()?
I recall I was having some problems with implementation so I made another function outside AreaDo()

**Comment by Bird-Bird** [comment] 2020-01-09 20:20
I have replaced the item paste job in AreaDo() to:
`        if job == "PASTE" then
          paste(info.items, item_track, as_start, as_end, pos_offset, first_tr,off)
          split_or_delete_items(item_track, item_data, as_start, as_end , 'del')
        end`

And the envelope paste job to:
`        if job == "PASTE" then
          paste_env(env_track, env_name, env_data, as_start, as_end, pos_offset, first_tr, #tbl.sel_info, off)
          del_env(env_track, as_start, as_end, pos_offset, job)
          reaper.Envelope_SortPoints(env_track)
        end`

I wasn't sure how to move the moving functionality inside **AreaDo()** so I just used the paste function for the demonstration. 
Normally it would have to look at the difference between the target and the original area and only delete the difference.

**Comment by GoranKovac** [comment] 2020-01-09 21:07
Well that looks good to me, Reapers native behavior is very similar so I will make this change. Thank you

**Comment by GoranKovac** [comment] 2020-01-09 22:58
Can you make a pull request of what you exactly done?

**Comment by Bird-Bird** [comment] 2020-01-09 23:35
Sorry for the delay, on it

**Comment by Bird-Bird** [comment] 2020-01-09 23:47
Could you create a test branch that I could create a pull request to?

**Comment by GoranKovac** [comment] 2020-01-10 09:30
DEV branch created

**Comment by GoranKovac** [comment] 2020-01-10 10:23
For now I do not see any misbehaviors while testing various move,copy operations.

**Comment by GoranKovac** [comment] 2020-01-10 10:42
Oh this PR also fixed moving only selected parts oh the items! Nice!

**Comment by GoranKovac** [comment] 2020-01-12 11:13
Latest DEV reintroduced envelope jobs. Please test

If everything is fine should we close this issue? New implementation solved this problem (at least I did not see any misbehaviors).

**Comment by Bird-Bird** [comment] 2020-01-12 11:34
Everything seems to be working fine! There is one thing I came across but I am not sure if it is intentional or not:
![Gf97464jfw](https://user-images.githubusercontent.com/55462109/72218128-93189280-3548-11ea-9e0f-4e67e0234fc4.gif)

The envelope gets pasted on the lane the mouse is over, even though the ghost displays it somewhere else.

**Comment by GoranKovac** [comment] 2020-01-12 12:03
Yeah that is Envelope-Override mode kicking in. Will disable that on drag operations if item is also selected

**Comment by GoranKovac** [comment] 2020-01-12 12:06
BTW I cannot reproduce that ?

**Comment by GoranKovac** [comment] 2020-01-12 12:09
Please try latest DEV since I've fixed few more stuff after I've added envelopes back:

Last commit adds DRAG-PASTE as separate job so it does not trigger standard paste flags

**Comment by GoranKovac** [comment] 2020-01-12 12:14
But also when envelopes only are selected it does not allow moving/copy them to other lanes. Fixing this

**Comment by Bird-Bird** [comment] 2020-01-12 12:18
Will test in a bit, working on item chunks

**Comment by GoranKovac** [comment] 2020-01-12 12:22
So I've found something by accident, something is really broken in V6. Because my envelopes are not working as they should. If you enter COPY-PASTE mode it does not detect envelope lanes , but it detects them in TRACK.

Tested the script again with reaper 5983 and everything works just fine. 
Need to report this to Justin

**Comment by Bird-Bird** [comment] 2020-01-12 12:25
It might be related to the new TCP architecture in V6, some SWS API functions and actions had to be fixed because of it as well.

**Comment by GoranKovac** [comment] 2020-01-12 12:27
That was introduced in DEV versions 5.9. I've ported the whole script then. Since it was not working at all

**Comment by GoranKovac** [comment] 2020-01-12 13:53
Issue seems to be BR API. Refactoring some functions that use it

**Closed** 2020-04-03 06:07 UTC
